### ISSUE TITLE
Does it work for EU domains?

### ISSUE THREAD

**Issue by jaimecosme** [sinch/node-red-mailgun#1]
I am struggling to make it work.

I think the problem is that I am an EU user and there is no option to choose wether to use a the global (https://api.mailgun.net) or the EU server (https://api.eu.mailgun.net).

Trying to access an EU account from the global server doesn't work

**Comment by sinchflows** [comment]
Hello, thanks for your feedback. You are correct, currently there is no support for EU region. This would make a good addition. An update for this will come in the next coming weeks. Most likely in the form of a region select option in the Send node configuration.

**Comment by sinchflows** [comment]
An update with support was published last month. We'll close this issue. Let us know if you face any other issues.
